server:
  port: 80002

spring:
  application:
    name: privider
dubbo:
  application:
    name: ${spring.application.name}
  registry:
    address: zookeeper://127.0.0.1:2181
    timeout: 2000
  # 用dubbo协议在20890端口暴露服务
  protocol:
    name: dubbo